// src/components/AnimatedText.tsx
import { motion } from 'framer-motion'

interface AnimatedTextProps {
	tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span'
	text: string
	delay?: number
	initialDelay?: number
	duration?: number
	className?: string
}

export function AnimatedText(
	{ tag, text, initialDelay = 0, delay = 0.1, duration = 0.5, className }: AnimatedTextProps,
) {
	const variants = {
		hidden: { opacity: 0, y: 20 },
		visible: { opacity: 1, y: 0 },
	}

	const Component = tag

	const letters = text.split('')

	let accumulatedDelay = initialDelay

	return (
		<Component
			className={className}
		>
			{letters.map((letter, index) => {
				if (letter.trim()) accumulatedDelay += delay

				return (
					<motion.span
						className="inline-block"
						key={index}
						initial="hidden"
						animate="visible"
						variants={variants}
						transition={{
							delay: accumulatedDelay,
							duration,
							type: 'spring',
							bounce: 0.5,

						}}
					>
						{letter.trim() || '\u00A0'}
					</motion.span>
				)
			})}
		</Component>
	)
}

// src/components/animated-text.svelte
<script lang='ts'>
	export let tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span'
	export let text = ''
	export let initialDelay = 0
	export let delay = 0.1
	let className = ''
	export { className as class }

	const letters = text.split('')

	function getDelays() {
		let accumulatedDelay = initialDelay

		return letters.map((letter) => {
			if (letter === ' ') return 0
			accumulatedDelay += delay
			return accumulatedDelay
		})
	}

	const delays = getDelays()
</script>

<svelte:element this={tag} class={className}>
	{#each letters as letter, index (`${letter}-${index}`)}
		<span class='inline-block' style='opacity: 0; animation-delay: {delays[index]}s'>
			{letter.trim() || '\u00A0'}
		</span>
	{/each}
</svelte:element>

<style>
	@keyframes enter {
		from {
			transform: translateY(20px);
			opacity: 0;
		}
		to {
			transform: translateY(0);
			opacity: 1;
		}

	}

	span {
		display: inline-block;
		animation: enter 0.3s cubic-bezier(0.34, 1.6, 0.64, 1) forwards;
	}
</style>
